#!/bin/bash

display_usage() { 
    echo -e "\nUsage: $0 SOURCE_DIR DEST_DIR\n" 
} 

if [  $# -le 1 ] ; then 
    display_usage
    exit 1
fi 
 
if [[ ( $# == "--help") ||  $# == "-h" ]] ; then 
    display_usage
    exit 0
fi 

SOURCE_DIR="$1"
DEST_DIR="$2"

if [ ! -d "$SOURCE_DIR" ] ; then
    echo "Source directory $SOURCE_DIR does not exist, or is not a directory"
    display_usage
    exit 2
fi

if [ ! -d "$DEST_DIR" ] && ! mkdir -p $DEST_DIR ; then
    echo "Destination directory $DEST_DIR does not exist, or is not a directory"
    display_usage
    exit 2
fi

if [ ! -w "$DEST_DIR" ] ; then
    echo "Destination directory $DEST_DIR is not writeable, or is not a directory"
    display_usage
    exit 3
fi

if ! which parallel > /dev/null ; then
    sudo apt-get update && sudo apt install -y parallel
fi

DIRJOBS=225
JOBS=225
find $SOURCE_DIR -mindepth 1 -type d -print0 | sed -z "s:$SOURCE_DIR\/::" | parallel --will-cite -j$DIRJOBS -0 "mkdir -p $DEST_DIR/{}"
find $SOURCE_DIR -mindepth 1 ! -type d -print0 | sed -z "s:$SOURCE_DIR\/::" | parallel --will-cite -j$JOBS -0 "cp -P $SOURCE_DIR/{} $DEST_DIR/{}"
